name: emu
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pyopenssl=0.16
- cryptography=1.4
- pyyaml=3.11
- curl=7.45.0
- icu=56
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx=1.4.1
- sphinx_rtd_theme
# wps
- pywps=4.0.0
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.2
- lxml=3.7
- libxslt=1.1.28
#- eventlet=0.16.1
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
  - eventlet==0.19.0
